### PR TITLE
Optional setting of random seed for debugging

### PR DESCRIPTION
**Pull request by dachengx**
Provide `seed` as a keyword argument of `Runner`, so that we can reproduce the result when debugging because it is deterministic. In productive usage, it might not be necessary.

### CODE REVIEW

**Comment by kdund** [comment]
I think this would also only be feasible if np.random is the _only_ module used for random numbers, right? Not sure if that is true at the moment?

**Comment by dachengx** [comment]
> I think this would also only be feasible if np.random is the _only_ module used for random numbers, right? Not sure if that is true at the moment?

Yes, I also had this concern. But `scipy` also uses seed same as `np.random`. So I think it is true for alea.

**Review by hammannr — COMMENTED** [review]
I ran some tests with the `unbinned_wimp_statistical_model_simple` and everything went as expected. But if @kdund has concerns/suggestions for improvement I'll leave the approval of this PR to him.

**Comment by kdund** [comment]
If just for testing, in fine with this then:)

**Pull request merged**
