### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by yuema137**
For some reason, it doesn't recognize the blueice installed via ssh url. https is sometimes unstable so ssh is more common for people to use. So I suggest changing the requirement to ssh.

### CODE REVIEW

**Review by hammannr — DISMISSED** [review]
Good suggestion! I thing ash is the way to go. Thanks Yue!

**Comment by hammannr** [comment]
Ah I just saw that our CI pipeline doesn't like it. I'll have a look later

**Comment by hammannr** [comment]
Unfortunately, I didn't find a quick fix. I think we could set up deploy keys to solve this but maybe @dachengx has a better idea? Otherwise, I'll try that later!

**Comment by dachengx** [comment]
> Unfortunately, I didn't find a quick fix. I think we could set up deploy keys to solve this but maybe @dachengx has a better idea? Otherwise, I'll try that later!

Usually, ssh authentication requires a valid ssh key, so it is not used for `requirement.txt`. I do not think there can be a quick fix.

**Comment by hammannr** [comment]
After reading a bit about it and trying to find a good solution, I agree @dachengx . @yuema137 maybe this is an issue with the container? Let's discuss this in tech-support and try to find a solution for you rather than changing the requirements

**Comment by dachengx** [comment]
Fixed by https://github.com/XENONnT/alea/pull/132 and https://github.com/JelleAalbers/blueice/pull/42

**Pull request closed without merging**
