### PR TITLE
Simplify file structure

### PR DESCRIPTION
**Pull request by dachengx**
Change the package version to `0.0.0`. 

Separate used and unwed functions in original `utils.py` to `utils.py` and `_utils.py`. 

The inherited unused files and folders are named `_*`.

### CODE REVIEW

**Comment by kdund** [comment]
I guess the idea is to have this be the first step towards clearing out now-deprecated binference code, right? So first into a _folder, and then later when replaced, we delete it?

**Comment by dachengx** [comment]
> I guess the idea is to have this be the first step towards clearing out now-deprecated binference code, right? So first into a _folder, and then later when replaced, we delete it?

Yes, exactly.

**Comment by dachengx** [comment]
And also do not use nested folders inside `alea/alea`.

**Review by kdund — APPROVED** [review]
Works for me.

**Pull request merged**
