### PR TITLE
Add file hash to blueice hash

### PR DESCRIPTION
**Pull request by hammannr**
So far, if you made changes to a template that was already cached by blueice, blueice would use the cached version instead of the new one. This PR solves this issue by computing the hash of each source's template file and adding it to the blueice source config.

### CODE REVIEW

**Comment by hammannr** [comment]
I checked that it works but quickly want to add a unittest and do a few more checks tomorrow.

**Comment by hammannr** [comment]
But if you already have any code-related suggestions @dachengx please let me know 😊

**Comment by hammannr** [comment]
Ohhh ok nvm -- it kills some unittests, I'll fix it tomorrow..

**Comment by dachengx** [comment]
For the pre-commit problem, you can either merge while ignoring it or implement this: https://github.com/PyCQA/docformatter/pull/287#issuecomment-2401028403

**Review by dachengx — APPROVED** [review]

**Pull request merged**
