### PR TITLE
Make error message more explicit that an excecutable is not found and…

### PR DESCRIPTION
**Pull request by kdund**
… how to fix

### CODE REVIEW

**Comment by dachengx** [comment]
@kdund For users they should append `.local/bin` to their `PATH` like `export PATH=$HOME/.local/bin`. For developers, they should append `$HOME/alea/bin`.

**Comment by kdund** [comment]
Is this in our current installation instructions? 

(Also, in a jupyter notebook, as far as I can tell, it does not run my .bash_profile anyways to set env)

**Comment by dachengx** [comment]
> Is this in our current installation instructions?
> 
> (Also, in a jupyter notebook, as far as I can tell, it does not run my .bash_profile anyways to set env)

Did you reopen the terminal and submit the jupyter job? Or run `source .bash_profile`?

**Comment by dachengx** [comment]
That information is not in the current instruction. We should add that.

**Comment by kdund** [comment]
> > Is this in our current installation instructions?
> > (Also, in a jupyter notebook, as far as I can tell, it does not run my .bash_profile anyways to set env)
> 
> Did you reopen the terminal and submit the jupyter job? Or run `source .bash_profile` before submitting?

I submit jupyter notebooks from my mac using

`ssh -v midway2 /home/kmoraa/Software/env_starter/start_jupyter.py`

and then I now do 
```
import os
os.environ["PATH"] += ":" + "/home/kmoraa/Software/alea/bin/"
os.environ["PATH"] += ":" + "/software/slurm-current-el7-x86_64/bin/"
```

Not quite successful yet-- utilix is not finding sbatch :/

**Comment by dachengx** [comment]
> I submit jupyter notebooks from my mac using
> 
> `ssh -v midway2 /home/kmoraa/Software/env_starter/start_jupyter.py`
> 
> and then I now do
> 
> ```
> import os
> os.environ["PATH"] += ":" + "/home/kmoraa/Software/alea/bin/"
> os.environ["PATH"] += ":" + "/software/slurm-current-el7-x86_64/bin/"
> ```
> 
> Not quite successful yet-- utilix is not finding sbatch :/

Do you want to submit jobs through jupyter notebook? Btw, `which alea-submission` can tell you the place of `alea-submission`. And I added `export PATH=$HOME/.local/bin:$HOME/local/bin:$PATH` to .bashrc.

**Review by dachengx — APPROVED** [review]

**Review by dachengx — APPROVED** [review]

**Pull request merged**
